---
# Setup: pre-commit install
# Upgrade: pre-commut autoupgrade
# Run: pre-commit run --all-files
# https://pre-commit.com/hooks.html
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
exclude: (.terraform.lock.hcl)|(.devcontainer/)|(.cache/)|(.artifacts/)|(node_modules/)|(.yarn)|(ansible/)|(.licenses/)
default_stages: [commit, push]

repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    # https://github.com/jumanjihouse/pre-commit-hook-yamlfmt#override-defaults
    # https://yaml.readthedocs.io/en/latest/example.html
    rev: 0.1.0     # or specific tag
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3     # or higher tag
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict, --config-file, .yamllint.yaml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-byte-order-marker
      - id: check-case-conflict
      # - id: detect-aws-credentials
      #   args: [--allow-missing-credentials]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        name: No large files, use artifacts for that
      - id: check-merge-conflict
        name: Prevent merge markers being committed
      - id: forbid-new-submodules
        name: Don't allow git submodules
      - id: end-of-file-fixer
      - id: fix-byte-order-marker

  # format json but allow comments in json
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
      # stages: ['commit']

  # https://pre-commit.com/#supported-languages
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.3.2
    hooks:
      - id: markdownlint-cli2
        args: [--fix]

  - repo: local
    hooks:
      # FIRST TIME SETUP:  GO111MODULE=on go get github.com/zricethezav/gitleaks/v4@latest
      - id: gitleaks
        name: gitleaks
        entry: gitleaks --commit=latest --no-git --format json --path=. --report=.artifacts/gitleaks.json --quiet
        language: system
        pass_filenames: false
        stages: [push]
      - id: trufflehog
        name: trufflehog
        entry: docker run --rm -v ${PWD}:/proj  dxa4481/trufflehog --exclude_paths .trufflehog-exclude --allow .trufflehog-allow.json file:///proj
        language: system
        pass_filenames: false
        stages: [push]
